/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Quinquee
 */
public class form_transaksi extends javax.swing.JFrame {

    /**
     * Creates new form form_transaksi
     */
    public form_transaksi() {
        initComponents();
        clear();
        database_connection();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmlh_b = new javax.swing.JTextField();
        cmb_nama = new javax.swing.JComboBox<>();
        hrg_j = new javax.swing.JTextField();
        jmlh_j = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        disc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dsc2 = new javax.swing.JRadioButton();
        dsc1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Total Bayar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Form Transaksi Penjualan barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nama Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Harga Jual");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah Jual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jmlh_b.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmlh_b.setText("jmlh_b");
        jPanel1.add(jmlh_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, -1));

        cmb_nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_nama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Televisi", "Mesin Cuci", "Kulkas" }));
        cmb_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_namaActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, -1));

        hrg_j.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hrg_j.setText("hrg_j");
        hrg_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrg_jActionPerformed(evt);
            }
        });
        jPanel1.add(hrg_j, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 130, -1));

        jmlh_j.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmlh_j.setText("jmlh_j");
        jmlh_j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmlh_jMouseExited(evt);
            }
        });
        jmlh_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlh_jActionPerformed(evt);
            }
        });
        jPanel1.add(jmlh_j, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 90, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 90, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 90, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Simpan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 90, 40));

        total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        total.setText("total");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 130, -1));

        disc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        disc.setText("disc");
        jPanel1.add(disc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Diskon Penjualan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah Bayar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        dsc2.setText("10%");
        dsc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsc2ActionPerformed(evt);
            }
        });
        jPanel1.add(dsc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        dsc1.setText("5%");
        dsc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsc1ActionPerformed(evt);
            }
        });
        jPanel1.add(dsc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dsc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsc2ActionPerformed
       double diskon,x;
        x=Double.parseDouble(jmlh_b.getText());
        if(dsc1.isSelected()){
            diskon=0.10*x;
        }
        else{
            diskon=0;
        }
        disc.setText(String.valueOf(diskon));
        
    }//GEN-LAST:event_dsc2ActionPerformed

    private void dsc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsc1ActionPerformed
        double diskon,x;
         x=Double.parseDouble(jmlh_b.getText());
        if(dsc1.isSelected()){
            diskon=0.05*x;
        }
        else{
            diskon=0;
        }
       
        disc.setText(String.valueOf(diskon));
        
    }//GEN-LAST:event_dsc1ActionPerformed

    private void hrg_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrg_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrg_jActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double bayar ;
        bayar = Double.parseDouble(jmlh_b.getText()) - Double.parseDouble(disc.getText());
        total.setText(String.valueOf(bayar));
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmb_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_namaActionPerformed

       int harga_b=0;
        if(cmb_nama.getSelectedItem()=="Televisi"){
            harga_b=1500000;
        }
        else if(cmb_nama.getSelectedItem()=="Mesin Cuci"){
            harga_b=1000000;
        }
        else if(cmb_nama.getSelectedItem()=="Kulkas"){
            harga_b=2000000;
        }
       hrg_j.setText(String.valueOf(harga_b));
    }//GEN-LAST:event_cmb_namaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try {
            sql = "INSERT INTO transaksi VALUES ('"+cmb_nama.getSelectedItem()+
            "','"+hrg_j.getText()+
            "','"+jmlh_j.getText()+
            "','"+jmlh_b.getText()+
            "','"+disc.getText()+
            "','"+total.getText()+
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan.....");
            clear();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal....." + e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jmlh_jMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmlh_jMouseExited
       int bayar ;
        bayar = Integer.parseInt(hrg_j.getText()) * Integer.parseInt(jmlh_j.getText() );
        jmlh_b.setText(String.valueOf(bayar));
    }//GEN-LAST:event_jmlh_jMouseExited

    private void jmlh_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlh_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlh_jActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_nama;
    private javax.swing.JTextField disc;
    private javax.swing.JRadioButton dsc1;
    private javax.swing.JRadioButton dsc2;
    private javax.swing.JTextField hrg_j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jmlh_b;
    private javax.swing.JTextField jmlh_j;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
private void clear(){
cmb_nama.setSelectedIndex(0);
hrg_j.setText("");
jmlh_j.setText("");
jmlh_b.setText("");
disc.setText("");
total.setText("");
cmb_nama.requestFocus();
}

private Connection con;
private Statement stat;

private String sql;

private void database_connection(){
   try {
       Class.forName("com.mysql.jdbc.Driver");
       System.out.println("Driver Found...");
       try {
           String url = "jdbc:mysql://localhost:3306/db_java?user=root&password=";
           con = DriverManager.getConnection(url);
           System.out.println("Connected.....");
           
       } catch (SQLException e){
           System.err.println("Not Connection.....");
       }
   } catch (ClassNotFoundException e){
       System.err.println("Driver Not Found!.......");
   }
}

}
